import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import random

# Use standard Sans-serif fonts for English labels
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['Arial', 'DejaVu Sans', 'Liberation Sans', 'Bitstream Vera Sans']
# Ensure negative signs display correctly, although not used here
plt.rcParams['axes.unicode_minus'] = False


def draw_network_comparison():
    # 1. Define nodes
    # Set up 12 nodes labeled V1 through V12 as shown in the images.
    nodes = [f"V{i}" for i in range(1, 13)]
    num_nodes = len(nodes)

    # 2. Create a base graph to define layout and the complete graph
    G_base = nx.Graph()
    G_base.add_nodes_from(nodes)

    # 3. Core: Define all node positions
    # Use circular_layout to arrange nodes in a fixed circle.
    # This ensures positions are identical across both plots for direct comparison.
    pos = nx.circular_layout(G_base)

    # =========================================================================
    # 4. Create Subplot A: Complex Partial Graph (Original Structure)
    # =========================================================================
    G_partial = nx.Graph()
    G_partial.add_nodes_from(nodes)
    
    # Manually define some edges to create a complex, sparse graph structure.
    # (These edges are representative of the complex structure in the image.)
    partial_edges = [
        ('V1', 'V2'), ('V1', 'V4'), ('V1', 'V12'), ('V1', 'V7'),
        ('V2', 'V3'), ('V2', 'V8'), ('V2', 'V6'),
        ('V3', 'V4'), ('V3', 'V5'), ('V3', 'V9'),
        ('V4', 'V10'), ('V4', 'V6'),
        ('V5', 'V6'), ('V5', 'V7'),
        ('V6', 'V11'), ('V6', 'V12'),
        ('V7', 'V8'), ('V7', 'V10'),
        ('V8', 'V9'),
        ('V9', 'V11'),
        ('V10', 'V11'),
        ('V11', 'V12'),
    ]
    G_partial.add_edges_from(partial_edges)

    # =========================================================================
    # 5. Create Subplot B: Complete Graph (All-to-All Connected)
    # =========================================================================
    # Use NetworkX's built-in function to generate a complete graph.
    G_complete = nx.complete_graph(nodes)
    
    # Ensure G_complete uses our specific V1-V12 node labels (mapping integer nodes generated by default).
    mapping = {i: nodes[i] for i in range(num_nodes)}
    G_complete = nx.relabel_nodes(G_complete, mapping)


    # =========================================================================
    # 6. Plotting and Layout
    # =========================================================================
    # Create a figure object
    fig = plt.figure(figsize=(16, 10))
    # Use GridSpec to control subplot and text positions precisely.
    gs = gridspec.GridSpec(2, 2, height_ratios=[1, 0.2], wspace=0.1, hspace=0.1)

    # Plot Graph A
    ax0 = fig.add_subplot(gs[0, 0])
    draw_graph_panel(G_partial, pos, ax0, "A. Complex Partial Graph", "V", edge_color='black', node_color='lightcyan')
    ax0.text(0.5, -0.05, "Represents an original, sparse, complex network.", size=12, ha='center', va='top', transform=ax0.transAxes)

    # Plot Graph B
    ax1 = fig.add_subplot(gs[0, 1])
    draw_graph_panel(G_complete, pos, ax1, "B. Complete Graph", "V", edge_color='royalblue', node_color='lightcyan')
    ax1.text(0.5, -0.05, "Represents a comprehensive correlation all-to-all dense connection network.", size=12, ha='center', va='top', transform=ax1.transAxes)

    # Add a central vertical divider line
    divider = fig.add_subplot(gs[:, 0])
    divider.axis('off')
    divider.plot([1.05, 1.05], [0.1, 0.9], color='darkgray', transform=divider.transAxes, linewidth=1.5)

    plt.tight_layout()
    plt.savefig("graph_comparison.png", dpi=300, bbox_inches='tight')

# Helper function: Draw a single graph panel
def draw_graph_panel(G, pos, ax, title, node_prefix, edge_color, node_color):
    # 1. Draw nodes
    nx.draw_networkx_nodes(G, pos, ax=ax, node_color=node_color, node_size=1000, edgecolors='black', linewidths=1.5)
    
    # 2. Draw node labels (V1, V2, etc.) using fixed Sans-serif English font
    nx.draw_networkx_labels(G, pos, ax=ax, font_size=12)
    
    # 3. Draw edges
    # Graph B uses 'royalblue' color, Graph A uses 'black'. Straight lines are default.
    nx.draw_networkx_edges(G, pos, ax=ax, edge_color=edge_color, width=1.2, alpha=0.8)

    # Set title with larger, bold font
    ax.set_title(title, fontsize=18, fontweight='bold', pad=20)
    
    # Hide axis ticks and labels for cleaner network diagram
    ax.axis('off')
    
    # Adjust axes limits to center the circular layout and prevent clipping.
    # (circular_layout ranges roughly from -1 to 1, add a small margin)
    x_values, y_values = zip(*pos.values())
    x_margin = 0.2
    y_margin = 0.2
    ax.set_xlim(min(x_values) - x_margin, max(x_values) + x_margin)
    ax.set_ylim(min(y_values) - y_margin, max(y_values) + y_margin)

def draw_random_walk_visualization(G, pos, start_node='V1', walk_length=6):
    """
    Pick a vertex, perform a random walk, and visualize it on a new canvas.
    Each vertex on the path is highlighted and connected back to the start vertex.
    """
    # 1. Perform Random Walk
    path = [start_node]
    current_node = start_node
    for _ in range(walk_length):
        neighbors = list(G.neighbors(current_node))
        if not neighbors:
            break
        next_node = random.choice(neighbors)
        path.append(next_node)
        current_node = next_node
    
    # 2. Create Figure and Axis for the new canvas
    fig, ax = plt.subplots(figsize=(10, 10))
    
    # 3. Draw the original graph in the background (faded)
    nx.draw_networkx_nodes(G, pos, ax=ax, node_color='lightgray', node_size=800, alpha=0.3, edgecolors='none')
    nx.draw_networkx_edges(G, pos, ax=ax, edge_color='lightgray', width=1, alpha=0.2)
    nx.draw_networkx_labels(G, pos, ax=ax, font_size=10, font_color='darkgray', alpha=0.5)
    
    # 4. Highlight path and start node
    path_nodes = list(dict.fromkeys(path)) # Unique nodes in path
    
    # Draw path edges (the sequence of the walk) with arrows
    path_edges = list(zip(path, path[1:]))
    nx.draw_networkx_edges(G, pos, edgelist=path_edges, ax=ax, edge_color='firebrick', 
                           width=2.5, alpha=0.8, arrows=True, arrowsize=20)
    
    # Draw lines from each node on the path back to the starting node
    for node in path_nodes:
        if node != start_node:
            x_start, y_start = pos[start_node]
            x_node, y_node = pos[node]
            ax.plot([x_node, x_start], [y_node, y_start], color='royalblue', 
                    linestyle='--', linewidth=1.5, alpha=0.6, zorder=1)

    # Draw nodes on the path
    nx.draw_networkx_nodes(G, pos, nodelist=path_nodes, ax=ax, node_color='gold', 
                           node_size=1000, edgecolors='black', linewidths=1.5)
    
    # Highlight start node specifically
    nx.draw_networkx_nodes(G, pos, nodelist=[start_node], ax=ax, node_color='tomato', 
                           node_size=1200, edgecolors='black', linewidths=2.5)
    
    # Redraw labels for path nodes to make them clear
    path_labels = {n: n for n in path_nodes}
    nx.draw_networkx_labels(G, pos, labels=path_labels, ax=ax, font_size=12, font_weight='bold')

    # 5. Styling
    ax.set_title(f"Random Walk Path Visualization\n(Starting from {start_node})", fontsize=18, fontweight='bold', pad=20)
    ax.axis('off')
    
    # Adjust limits
    x_values, y_values = zip(*pos.values())
    x_margin, y_margin = 0.25, 0.25
    ax.set_xlim(min(x_values) - x_margin, max(x_values) + x_margin)
    ax.set_ylim(min(y_values) - y_margin, max(y_values) + y_margin)
    
    plt.tight_layout()
    plt.savefig("random_walk_path.png", dpi=300, bbox_inches='tight')
    print(f"Random walk path: {' -> '.join(path)}")
    print("Saved to random_walk_path.png")

if __name__ == "__main__":
    # To use G_partial and pos from draw_network_comparison, we can return them or redefine.
    # For simplicity, let's redefine the core parts here or modify the original function to return them.
    
    # Re-call original plotter (this saves graph_comparison.png)
    draw_network_comparison()
    
    # Now generate the second plot on a new canvas
    # We need G_partial and pos. Let's recreate them quickly or refactor.
    nodes = [f"V{i}" for i in range(1, 13)]
    G_partial = nx.Graph()
    G_partial.add_nodes_from(nodes)
    partial_edges = [
        ('V1', 'V2'), ('V1', 'V4'), ('V1', 'V12'), ('V1', 'V7'),
        ('V2', 'V3'), ('V2', 'V8'), ('V2', 'V6'),
        ('V3', 'V4'), ('V3', 'V5'), ('V3', 'V9'),
        ('V4', 'V10'), ('V4', 'V6'),
        ('V5', 'V6'), ('V5', 'V7'),
        ('V6', 'V11'), ('V6', 'V12'),
        ('V7', 'V8'), ('V7', 'V10'),
        ('V8', 'V9'),
        ('V9', 'V11'),
        ('V10', 'V11'),
        ('V11', 'V12'),
    ]
    G_partial.add_edges_from(partial_edges)
    pos = nx.circular_layout(G_partial)
    
    # Select a starting node, e.g., 'V1'
    draw_random_walk_visualization(G_partial, pos, start_node='V1', walk_length=6)